# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de45207897f42d7c9e09ad8ca5f664f7ac820a054eee10d5e2c9ff769260bf0239312b6b1c6cf96ceaef40d3884f03815963e4fdb05acc4d1b3ce7e94862fe1f

test:
  secret_key_base: 4d21e536ce25cd9527dc89ae765ee80a0fc1d47d933a2f3e1c7a58f014862e2298587efb51fd21ac37d6201c0eb81c07a5470dc2e85abf805f56faf59b869897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
